### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by IanKBovard**
Added new icon for apps, renamed old apps icon to grid-option

apps
Screen Shot 2020-07-15 at 3 31 49 PM

Replaced Clock, help, license, and keyboard

clock
Screen Shot 2020-07-15 at 3 33 39 PM

help
Screen Shot 2020-07-15 at 3 33 57 PM

license
Screen Shot 2020-07-15 at 3 34 32 PM

keyboard
Screen Shot 2020-07-15 at 3 31 27 PM

added webcam
Screen Shot 2020-07-15 at 3 35 38 PM

added new shareoption, renamed old shareoption to linkoption
Screen Shot 2020-07-15 at 3 36 05 PM

### CODE REVIEW

**Comment by ShimiSun** [comment]
> renamed old apps icon to grid-option
This wouldn't be backward compatible for the users.

**Comment by ShimiSun** [comment]
I think we would have a problem with icons that are renamed due to backward compatibility.
In order not to block the new icons, can you please separate the new icons to a separate PR?

**Comment by IanKBovard** [comment]
can do

**Comment by IanKBovard** [comment]
closing this pr to split into two

**Pull request closed without merging**
