### PR TITLE
Editor icons :

### PR DESCRIPTION
**Pull request by atanasster**
1. BlockQuote - #29 
2. Bold - #20 
3. Emoji - #32 
4. Italic - #21 
5. Monospace - #22 
6. OrderedList - #27 
7. Redo - #31 
8. RotateLeft - #14 
9. RotateRight - #15 
10. StrikeThrough - #24 
11. Subscript - #25 
12. Superscript - #26 
13. TextAlignCenter - #16 
14. TextAlignFull - #17 
15. TextAlignLeft - #18 
16. TextAlignRight - #19 
17. Underline - #23 
18. Undo - #30 
19. UnorderedList - #28

### CODE REVIEW

**Comment by alansouzati** [comment]
This is amazing. thanks for the contribution.

I should probably write this somewhere, but the process to generate an icon as a react component is automated. We have a [script](https://github.com/grommet/grommet-icons/blob/master/tools/generate-icons.js) that goes over the raw svgs and transforms them into React components.

That said, would you mind adding the new icons as raw svgs in this folder:

https://github.com/grommet/grommet-icons/tree/master/public/img

Composite names are expected to be dash-separated, for example: `text-align-center.svg`.

You can take a look on the existing raw svgs and follow the same structure, as you did for the react icons.

As you as you have the icons as raw svgs you can run two commands:

1) `npm run generate-icons`
2) `npm run test-update`

**Comment by atanasster** [comment]
Now I understand why on the first try my react icon files disappeared and I had to re-create them again manually a second time - I used the npm run generate-icons but assumed it is just a test to generate release icons :)
I believe I have now commited the correct files, but a note on how to contribute would be great if someone else gets confused. 
Also - any insight on the Code Climate issues, just ignore them ?

**Comment by alansouzati** [comment]
yeah dont worry about them. I have to investigate how to disable that check. it does not make sense for us to improve those "replications".

Sorry to hear that you lost your icons. 

Can you create a `CONTRIBUTING.md` file in the root of this project explaining the process you took to create these awesome icons?

**Comment by atanasster** [comment]
CONTRIBUTING.md - of course  (never heard of it, but will search around :))

**Comment by alansouzati** [comment]
here is one example:

https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md

**Pull request merged**
