### PR TITLE
Optimize svgs

### PR DESCRIPTION
**Pull request by samuelgoff**
Adds multipass SVGO optimization to generate-icons script to achieve visually-lossless compression roughly 63% of originals.

BEFORE (left) vs AFTER (right):
Screen Shot 2021-05-08 at 2 20 40 PM

### CODE REVIEW

**Comment by ShimiSun** [comment]
Can you please provide a little background on why you think this package is beneficial and why do you have to make the code changes per icon after adding it?

**Comment by samuelgoff** [comment]
> Can you please provide a little background on why you think this package is beneficial and why do you have to make the code changes per icon after adding it?

Hey @ShimiSun, No problem:

1. The original SVGs are preserved, so there is no loss of data.
2. From my previous work on this repo, I was surprised to notice there is no process in place to optimize SVGs. To my way of thinking, optimizing web graphics is a best practice, regardless of whether it is raster or vector format.
2. I did not have to make code changes per icon, and that's the point. I added SVG optimization to the `generate-icons` script, which then automatically optimizes the SVG data as part of the process of running the script. The result is that every existing SVG icon becomes an average of 27% smaller, and newly-added SVG icons will also be automatically optimized, without the contributor having to worry about it. With the exception of the 2 icons I recently contributed to the repo (which were already optimized by me as a matter of S.O.P.), the reason every other icon in the repo is impacted by running this script is because they are encoded in a less-than-optimal format.
3. Smaller files download faster. For example, the GraphQL logo is only 28% of original file size, a **72% reduction** in download time. Docker is 31% smaller, a 69**% reduction** in download time. Hundreds of these SVGs achieve >50% file size (and network bandwidth) savings, but the overall average result is files that are 63% of the original size load in 63% of the time.
Screen Shot 2021-05-10 at 4 37 33 PM
4. I've been using SVGO since it was released 9 years ago. With almost 12 million npm downloads per week, [SVGO](https://www.npmjs.com/package/svgo) is widely trusted and recognized as being one of the best SVG (open source) optimizers out there. It is the basis for Jake Archibald's [SVGOMG](https://jakearchibald.github.io/svgomg/), as well as thousands of other tools, including the `@svgr/plugin-svgo@^4.3.1` webpack plugin that's already used in this repo, albeit a much older vintage (1.2.2). I chose to include the latest version (2.3.0) because it is more effective than the older version. I judged this to be the least-invasive change versus forcing a bump in webpack dependency, while still maximizing the benefit.
5. Because it is a dev-only dependency, the `generate-icons` script is the only thing impacted by SVGO, and it is not included with any `dist` files, so to my way of thinking, it is extremely safe.
6. Results are visually lossless. If you open up each icon side-by-side with the original, you will not be able to tell the difference. (If you _can_ discern a difference, I'll buy you a beer and then go double-or-nothing for you to tell me which is which 🙂) If the results look the same but load faster, then why wouldn't you take advantage of it?

> Your web app loads way too fast...
(...said nobody, ever)

**Review by ericsoderberghp — DISMISSED** [review]

**Comment by ShimiSun** [comment]
Great PR! We love to see this type of library optimizations!
We had a couple of discussions on the approach, we are supportive of the overall goal of optimizing the size of the icons. However, we are wondering if can do it without increasing the package bundle size of adding `svgo` package https://packagephobia.com/result?p=svgo of 4.26MB, which is heavier than the entire package size of grommet-icons (3.79MB)

**Comment by samuelgoff** [comment]
> We had a couple of discussions on the approach, we are supportive of the overall goal of optimizing the size of the icons. However, we are wondering if can do it without increasing the package bundle size of adding `svgo` package https://packagephobia.com/result?p=svgo of 4.26MB, which is heavier than the entire package size of grommet-icons (3.79MB)

That's odd. `npm` says `svgo` is only [907kB unpacked](https://www.npmjs.com/package/svgo), whereas it says `grommet-icons` is [3.94MB unpacked](https://www.npmjs.com/package/grommet-icons) -- roughly in agreement with what packagephobia.com reports for `grommet-icons`, but obviously **_way off_** -- by a factor of 5 -- with regards to `svgo`.

I understand your concern. If `svgo` were part of the distribution, I would agree 100%. However, this is a dev-only dependency, which means the **only** people who are going to be impacted by it are ones who are adding/maintaining icons & running the `generate-icons` script, not people who are simply consuming the icons themselves. IMO, such a use is perfectly reasonable and acceptable.

The current version of `svgo` is this size because SVGs can be incredibly complex, and this is a library designed to handle any SVG the spec allows for. Previous versions didn't handle optimization or fidelity to the original nearly as well, or they made it display fine but impossible to edit after the fact. From what I've seen, the current version is a big step forward in all of these measures.

There are alternatives to `svgo`, but they do not have nearly as many users, and in most cases, they don't work as well (I've tried several). `svgo` gets anywhere from 8.7 million to 12 million npm downloads per week, compared to the next-most popular solution gets only 1.5 million per week. Having used many of these alternatives, I don't think this disparity in popularity is an accident. 

For all of these reasons, I feel like the use of `svgo` is the best fit for the task at hand.

> As an alternative, we are inclined to maybe run the SVG optimizations on the source files and let the svg be optimized independently, without the need of adding an external package to complete the task. Let us know what you think.

I would recommend against that approach. Here's why:

- In general, when creating an image-processing pipeline, you want to preserve the original files without throwing away any information. These files are highly maintainable, because paths, objects, and layers are kept in their original, separate form with human-readable names. Vector editing software can easily work with them, and humans are the target audience for this type of file.
- Optimizing for Web delivery aims for smallest possible file size, so the "target audience" is the network and the browser -- while ensuring things look imperceptible from the originals (a.k.a. "visually lossless") -- regardless of how inscrutable the optimized files are for humans. Separate paths, objects, & layers are often discarded or combined and flattened into as few separate elements as possible. Information is intentionally thrown out in the optimization process, and (in general) you want that to be the last possible step in an image processing pipeline.
 
In my experience, if you decide to throw out information at the beginning of your image processing pipeline, this will eventually come back to bite you.

One alternative you might consider is to use separate repos for (1) source vs (2) optimized svgs. For that matter, you could have a separate repo containing only the (3) JS files. This way, the dependencies necessary to build the next step in the pipeline could be limited only to the repo that consumes or publishes a resource, depending on how you'd like to structure it. This would be more work to maintain separate repos, but it would give you the smallest possible package size for the format that most people care about, which is the distributed JS files, while also limiting file size for the optimization part of the pipeline. However, with module imports and modern tree-shaking features, I don't think this is a good way to optimize for the humans that have to work with and maintain these repos.

That said, if it were me, I'd just be at peace with using `svgo` in the current repo, because IMO it's the right tool for the job, and it's intentionally placed at exactly the right place in the image processing pipeline.

**Comment by ShimiSun** [comment]
I agree with your statement about svgo being a dev-dependency hence would not affect the distribution package.

Let me take another look at this PR and I'll follow up.

**Review by ShimiSun — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]

**Pull request merged**
