### PR TITLE
Fix Moon icon

### PR DESCRIPTION
**Pull request by ShimiSun**
Replacing path to fix the icon display.
Fixes https://github.com/grommet/grommet-icons/issues/180

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
Something still looks incorrect. I'm looking at https://deploy-preview-185--hungry-raman-b31556.netlify.app/?selectedKind=Icon&selectedStory=Color&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs, where I set the icon to "Moon", it fills with "attention" color but still has a black stroke.

**Comment by ShimiSun** [comment]
Thanks for raising the concern, I was under the impression its a feature :)
Can @saggiemilva or @L0ZZI confirm whether this is the right behavior? 
image
Available on the Netlify deployment (above) as well.

**Comment by ericsoderberghp** [comment]
If you try other icons, they don't behave that way, at least the ones I ran through. They change the stroke color to the requested color and have no fill color.

**Comment by L0ZZI** [comment]
Urg...Export issues! 

Here is the Sketch export, 

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path fill="none" stroke="#000" stroke-linejoin="round" stroke-width="2" d="M15,1 C17.3586065,1 19.5438338,1.74232502 21.3347945,3.00608783 C21.2236156,3.00204754 21.1120469,3 21,3 C16.0294373,3 12,7.02943725 12,12 C12,16.9705627 16.0294373,21 21,21 C21.1120469,21 21.2236156,20.9979525 21.3347945,20.9938927 C19.5438338,22.257675 17.3586065,23 15,23 C8.92486775,23 4,18.0751322 4,12 C4,5.92486775 8.92486775,1 15,1 Z"/>
</svg>`

and here is the Figma export, 

`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.87429 5.00768C12.6018 3.32868 16.4785 3.99425 18.1232 5.20514C15.169 6.04476 13.0146 8.47225 12.8822 11.6196C12.7022 15.8991 15.8883 18.2077 18.1228 18.772C16.1584 20.1153 13.7623 20.0653 12.8867 19.9445C9.31874 19.4524 5.98538 16.5111 5.87974 12.233C5.77411 7.95486 8.4525 5.88291 9.87429 5.00768Z" stroke="black" stroke-width="2" stroke-linejoin="round"/>
</svg>`

The big diff I see is where the `fill="none"` is placed. I don't know why Figma would put that in `<svg>`. Other than the name vs. the hex for color values I would assume that should be fine. You all see anything else?

**Comment by ShimiSun** [comment]
Moving `fill=none` from the <svg /> to <path /> is still not looking perfect

image

**Comment by ShimiSun** [comment]
I took a second look at this issue and I think it was already solved on #186.

**Comment by ShimiSun** [comment]
I took a second look at this PR, and I think the issue is already solved on #186.

**Pull request closed without merging**
