### PR TITLE
Added the Kubernetes icon

### PR DESCRIPTION
**Pull request by bowdeng**
Noticed the script to create icons added a class='cls-1' which the linter didn't like. Removed it with apparently no ill effects.

### CODE REVIEW

**Comment by ShimiSun** [comment]
Hi buddy, I see the PR deployment had failed, did you follow the instructions on [CONTRIBUTING.md](https://github.com/grommet/grommet-icons/blob/master/CONTRIBUTING.md)?

**Comment by bowdeng** [comment]
Hi Shimi

Yup. Looking at the logs it seems to be when it was preparing the repo which suggests it had problems communicating with my forked version. I tried anonymously cloning and it was fine so I’m a bit confused. All the tests locally ran and after some cleaning up the pre-commit hooks all passed too. I’ll have a play again today but if you’ve any ideas what might have occurred happy to try again. 

Glyn

**Comment by ShimiSun** [comment]
Thanks buddy! @L0ZZI can you please approve the svg before I'll attempt to fix this branch?

**Comment by vavalos5** [comment]
The SVG looks good!

**Comment by bowdeng** [comment]
This has been open a while now and the main is very far ahead

**Pull request closed without merging**
