### PR TITLE
Feat/pocket

### LINKED ISSUE #146: Add Pocket Icon
Please add an icon for [Pocket](https://getpocket.com)

### PR DESCRIPTION
**Pull request by krichdev**
Adding [Pocket](https://getpocket.com) logo to icon library.

Closes #146

### CODE REVIEW

**Comment by ShimiSun** [comment]
adding @L0ZZI to review the svg.
@krichdev can you fix the failures by following the instructions on the contributing.md file?

**Comment by krichdev** [comment]
> adding @L0ZZI to review the svg.
> @krichdev can you fix the failures by following the instructions on the contributing.md file?

@ShimiSun thank you - I ran that before first PR. Did it again, but looks like still getting hung up on the code climate check?

**Comment by L0ZZI** [comment]
Looks good @krichdev. Thanks for the contribution!

**Comment by ShimiSun** [comment]
Thanks @krichdev looks good.
I filed a separate PR that supposed to fix the issue/failure this PR is running into #150. 
After #150 is merged we'll recompile this PR and make sure tests are passing as expected before merging. Thanks for your patient.

**Comment by ShimiSun** [comment]
hi buddy, thanks for the PR, @krichdev, unfortunately, the svg isn't rendering.

Can you update your branch, run `yarn storybook` and replace on https://github.com/grommet/grommet-icons/blob/d377a346c20bf374fb9a6a45caa52c1c42a07de4/src/js/icon.stories.js#L45
The reference of `Facebook` to your icon and see weather it renders correctly on storybook? it will be a good indication and confirmation that the icon is valid

**Comment by ShimiSun** [comment]
The issue above is fixed with PR #151

**Pull request merged**
