### PR TITLE
added Insecure icon & alphabetized metadata

### PR DESCRIPTION
**Pull request by samuelgoff**
Addresses the need for an explicit `Insecure` icon, to be swapped in-place with the existing `Secure` icon. One of the design goals is for this to remain perfectly registered with the `Secure` icon to prevent repositioning/jank as the icons get swapped (e.g. icon button or validation). For this reason, the existing `Lock` vs `Unlock` icons won’t work very well.

Slack discussion regarding this topic can be found [here](https://grommet.slack.com/archives/C04LMHN59/p1620760134150600).

In response to feedback from @ericsoderberghp:

> My initial thought was to make the “gap” larger between the loop & body of the lock, but (bizarrely) this caused an optical illusion such that the connected side then looked wavy. I iterated on this quite a few times and ended up with something that differentiates a bit more while still intentionally playing off the Secure proportions. I can’t go edge-to-edge with the “x” without making it look like Professor Xavier’s wheelchair or something else cheesy, so this is the best compromise I could come up with that balances against all the other design considerations I’m juggling.

>  one more approach would be to simply make it a “minus” sign

> The – has the added benefit of greater similarity to the existing Unlock icon and “–” symbol also conveys “without” / “negative” / “minus”. (I think I’ve talking myself into preferring the “minus” version)

Screen Shot 2021-05-11 at 4 59 27 PM

### CODE REVIEW

**Comment by ShimiSun** [comment]
Thank you for this PR!

Any reason GL are not adapting the original grommet-icons of lock/unlock?
https://icons.grommet.io/?s=lock
https://icons.grommet.io/?s=unlock

Instead of adding a new flavor of locks? We are trying to stay away from icon duplications unless there is a functional need.

**Comment by samuelgoff** [comment]
> Thank you for this PR!
> 
> Any reason GL are not adapting the original grommet-icons of lock/unlock?
> https://icons.grommet.io/?s=lock
> https://icons.grommet.io/?s=unlock
> 
> Instead of adding a new flavor of locks? We are trying to stay away from icon duplications unless there is a functional need.

Hi @ShimiSun, the `Secure` already exists in the repo, so presumably the decision was already made that there was a need for an icon to convey the concept of "secure" versus "locked". And while the "unlocked" version exists, an "insecure" does not.

As I discussed in Slack and this PR:
> One of the design goals is for this to remain perfectly registered with the `Secure` icon to prevent repositioning/jank as the icons get swapped (e.g. icon button or validation). For this reason, the existing `Lock` vs `Unlock` icons won’t work very well.

Also, IMO, the `Secure` icon looks better than the `Lock` icon.

If you think there is no need for a separate `Lock` vs `Secure` (nor `Unlock` vs `Insecure`) icon, my preference would be to combine the best aspects of each of the two designs into one (`Lock` + `Secure`, as well as `Unlock` + `Insecure`) -- while maintaining the design goal of maintaining proper registration between the two. I like the overall shape of the `Secure` icon & keyhole best, whereas the `Unlock` swivels the shackle/shank 180º to the left, so it's more immediately apparent that it's unlocked, even at small sizes. Unfortunately, the Unlock is a completely different width than the Lock icon, so they are not in registration with each other. As a result, if the "swiveled" treatment of the `Unlock` is to be maintained, one change would be the `Lock` icon would no longer be perfectly centered, so that swapping between the 2 doesn't cause any jank. Like so:
secure-02-01
insecure-07-01

Is this an acceptable solution?

**Comment by ShimiSun** [comment]
> the Secure already exists in the repo, so presumably, the decision was already made that there was a need for an icon to convey the concept of "secure" versus "locked". And while the "unlocked" version exists, an "insecure" does not.

I agree, thank you for clarifying.

**Comment by ShimiSun** [comment]
As I mentioned above, I agree with the overall approach of adding this icon.
I'm now looking at the design of the icon, and here is a thought:
With the design of 'Unlock' it is clear we are unlocking a functionality since the handle of the lock is turned to the other side, any reason you decided to approach 'Insecure' in a way that doesn't turn the handle to the other side? (I'm asking for consistency)

**Comment by samuelgoff** [comment]
> As I mentioned above, I agree with the overall approach of adding this icon.
> I'm now looking at the design of the icon, and here is a thought:
> With the design of 'Unlock' it is clear we are unlocking a functionality since the handle of the lock is turned to the other side, any reason you decided to approach 'Insecure' in a way that doesn't turn the handle to the other side? (I'm asking for consistency)

Hey @ShimiSun, I discussed this immediately above:

>Unfortunately, the `Unlock` is a completely different width than the `Lock` icon, so they are not in registration with each other. As a result, if the "swiveled" treatment of the `Unlock` is to be maintained, one change would be the `Lock` icon would no longer be perfectly centered, so that swapping between the 2 doesn't cause any jank. Like so:
secure-02-01
insecure-07-01

Contrast this to the design I included with this PR:
secure-current-01
insecure-current-01

^ The design in the current PR prevents the need to have an icon off-centered, while maintaining proper registration, so that if the icons are swapped between each other, there is no repositioning (bank) with the icon(s).

However, if you are okay with the off-centered `Secure` icon (shown at top) with placeholder negative space to accommodate the swiveled shank, I can push the design at top.

**Review by ShimiSun — APPROVED** [review]
Good stuff, thank you for your contribution!

**Pull request merged**
